/*
 * Copyright 2021, Francois Ritaly
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import 'dart:io';

void trace(String message) {
  stderr.writeln("${message}");
}

class Generator implements Iterator<int> {
  final int m, a;
  int _current;

  Generator(this.m, this.a, int s) {
    _current = s;
  }

  @override
  int get current => _current;

  int computeNext(int current) {
    // X(n+1) = A * X(n) % M
    return (a * current) % m;
  }

  @override
  bool moveNext() {
    _current = computeNext(_current);

    return true;
  }
}

void main() {
  var inputs = stdin.readLineSync().split(' ');
  var M = int.parse(inputs[0]);
  var A = int.parse(inputs[1]);
  var S = int.parse(inputs[2]);
  var N = int.parse(inputs[3]);

  trace("${M} ${A} ${S} ${N}");

  // List containing the array generated by the LGC
  var array = List<int>(N);

  var generator = Generator(M, A, S);

  for (int i = 0; i < N; i++) {
    generator.moveNext();

    array[i] = generator.current;
  }

  // trace("${array}");

  var count = 0;

  for (var i = 0; i < array.length; i++) {
    for (var j = 0; j < i; j++) {
      if (array[j] > array[i]) {
        count++;
      }
    }
  }

  print(count);
}